CREATE TABLE content (
  `key` VARCHAR(64) NOT NULL PRIMARY KEY,
  `value` TEXT NOT NULL,
  `type` ENUM('text','image') NOT NULL DEFAULT 'text',
  `updated_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE content_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(64) NOT NULL,
  old_value TEXT NOT NULL,
  changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE properties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image VARCHAR(500) NOT NULL DEFAULT '',
  name VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO properties (image, name, description, sort_order) VALUES
('https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80', 'Fastighet 1 – fyll i adress', 'Kort beskrivning av fastigheten – redigera i adminläget.', 1),
('https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80', 'Fastighet 2 – fyll i adress', 'Kort beskrivning av fastigheten – redigera i adminläget.', 2),
('https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80', 'Fastighet 3 – fyll i adress', 'Kort beskrivning av fastigheten – redigera i adminläget.', 3),
('https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80', 'Fastighet 4 – fyll i adress', 'Kort beskrivning av fastigheten – redigera i adminläget.', 4);

INSERT INTO content (`key`, `value`, `type`) VALUES
('topbar.badge_1', 'Karlskrona med omnejd', 'text'),
('topbar.badge_2', 'F-skatt', 'text'),
('topbar.badge_3', 'Ansvarsförsäkrad', 'text'),
('topbar.badge_4', 'ROT-avdrag', 'text'),
('hero.overline', 'Bygg & fastighetsservice i Karlskrona', 'text'),
('hero.title', 'Badrumsrenovering,', 'text'),
('hero.title_accent', 'bygg och fastighetsservice', 'text'),
('hero.subtitle', 'PIFAST AB utför allt från badrumsrenoveringar och köksrenoveringar till dörr- och fönsterbyten, ombyggnationer och löpande fastighetsservice. Vi samordnar även med elektriker och rörfirma.', 'text'),
('hero.button_secondary_label', 'Våra tjänster', 'text'),
('hero.image', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=85', 'image'),
('hero.caption', 'Kvalitet från start till mål', 'text'),
('hero.badge_1', 'Far & son\nsedan 2012', 'text'),
('hero.badge_2', 'Lokalt i\nNättraby', 'text'),
('hero.badge_3', 'Kvalitet\ni varje detalj', 'text'),
('intro.overline', 'Välkommen till Pifast', 'text'),
('intro.heading', 'En trygg kontakt från start till mål.', 'text'),
('intro.paragraph', 'Vi är far och son som drivit Pifast sedan 2012. Vi tar oss an både enskilda renoveringar och löpande hjälp med fastigheten – med erfarenhet, ordning och reda.', 'text'),
('services.overline', 'Våra tjänster', 'text'),
('services.heading', 'Vi hjälper dig med', 'text'),
('services.1.title', 'Badrumsrenovering', 'text'),
('services.1.body', 'Vi utför kompletta badrumsrenoveringar, från rivning till färdigt badrum. Vi samordnar med behöriga elektriker och rörfirma.', 'text'),
('services.1.image', 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=700&q=80', 'image'),
('services.2.title', 'Köksrenovering', 'text'),
('services.2.body', 'Vi hjälper dig att förverkliga dina köksdrömmar, från planering till färdigt resultat.', 'text'),
('services.2.image', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=700&q=80', 'image'),
('services.3.title', 'Dörrar och fönster', 'text'),
('services.3.body', 'Vi byter och monterar dörrar och fönster, både vid renovering och nybyggnation.', 'text'),
('services.3.image', 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=700&q=80', 'image'),
('services.4.title', 'Bygg och fastighetsservice', 'text'),
('services.4.body', 'Vi utför ombyggnationer, mindre byggprojekt och löpande fastighetsservice för både privatpersoner och företag.', 'text'),
('services.4.image', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=700&q=80', 'image'),
('about.overline', 'Om PIFAST AB', 'text'),
('about.heading', 'Ett familjeföretag med lång erfarenhet', 'text'),
('about.paragraph', 'PIFAST AB är ett familjeföretag som drivs av far och son sedan 2012. Vi är baserade i Karlskrona och utför uppdrag i närområdet. För oss är personlig kontakt, kvalitet och nöjda kunder viktigast.', 'text'),
('about.list.1', 'Familjeföretag sedan 2012', 'text'),
('about.list.2', 'Samordning med elektriker och rörfirma', 'text'),
('about.list.3', 'Godkända för F-skatt och ansvarsförsäkrade', 'text'),
('about.button_label', 'Läs mer om oss', 'text'),
('about.image', 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85', 'image'),
('about.caption', 'Far & son sedan 2012', 'text'),
('about.map_label', 'Lokalt i Nättraby', 'text'),
('about.feature_1.label', 'Familjeföretag', 'text'),
('about.feature_1.text', 'Far och son sedan 2012', 'text'),
('about.feature_2.label', 'Kvalitet', 'text'),
('about.feature_2.text', 'Vi gör jobbet ordentligt', 'text'),
('about.feature_3.label', 'Helhetslösningar', 'text'),
('about.feature_3.text', 'Vi samordnar med elektriker och rörfirma', 'text'),
('about.feature_4.label', 'Karlskrona med omnejd', 'text'),
('about.feature_4.text', 'Vi utgår från Karlskrona', 'text'),
('gallery.1.image', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80', 'image'),
('gallery.1.name', 'Projekt 1 – fyll i namn', 'text'),
('gallery.1.location', '', 'text'),
('gallery.2.image', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80', 'image'),
('gallery.2.name', 'Projekt 2 – fyll i namn', 'text'),
('gallery.2.location', '', 'text'),
('gallery.3.image', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80', 'image'),
('gallery.3.name', 'Projekt 3 – fyll i namn', 'text'),
('gallery.3.location', '', 'text'),
('gallery.4.image', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80', 'image'),
('gallery.4.name', 'Projekt 4 – fyll i namn', 'text'),
('gallery.4.location', '', 'text'),
('trust.heading', 'Vi jobbar seriöst och säkert', 'text'),
('trust.badge_4', 'Samarbete med behöriga yrkesgrupper', 'text'),
('trust.badge_5', 'Följer Byggkeramikrådets rekommendationer', 'text'),
('contact.overline', 'Kontakt', 'text'),
('contact.heading', 'Har du ett projekt på gång?', 'text'),
('contact.paragraph', 'Kontakta oss så diskuterar vi hur vi kan hjälpa dig.', 'text'),
('contact.button_label', 'Kontakta oss', 'text'),
('contact.caption', 'Kvalitet från start till mål', 'text'),
('contact.image', 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1800&q=80', 'image'),
('contact.phone', '0709-505516', 'text'),
('contact.email', 'patrik@pifastab.se', 'text'),
('contact.address', 'Idrottsvägen 5\n370 24 Nättraby', 'text'),
('contact.bankgiro', '883-3873', 'text'),
('footer.org_number', '556899-6499', 'text'),
('footer.tax_status', 'Godkänd för F-skatt', 'text'),
('footer.facebook_url', '', 'text');
